// flow-typed signature: 0a8f1868d0146242572a5cd63c0f4c89
// flow-typed version: <<STUB>>/lodash.defaults_v^4.2.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.defaults'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.defaults' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.defaults/index' {
  declare module.exports: $Exports<'lodash.defaults'>;
}
declare module 'lodash.defaults/index.js' {
  declare module.exports: $Exports<'lodash.defaults'>;
}
