// flow-typed signature: 0902e38a144d5cf0bf4cbe267f9f5fe6
// flow-typed version: <<STUB>>/@jedwards1211/eslint-config-react_v^2.0.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@jedwards1211/eslint-config-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@jedwards1211/eslint-config-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@jedwards1211/eslint-config-react/index' {
  declare module.exports: $Exports<'@jedwards1211/eslint-config-react'>;
}
declare module '@jedwards1211/eslint-config-react/index.js' {
  declare module.exports: $Exports<'@jedwards1211/eslint-config-react'>;
}
